<a href="https://colab.research.google.com/github/DavidSenseman/BIO3523/blob/main/BIO3523_Class_02_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<!-- BIO3523_Class_02_4:Rev 1 -->

---------------------------
**COPYRIGHT NOTICE:** This Jupyterlab Notebook is a Derivative work of [Jeff Heaton](https://github.com/jeffheaton) licensed under the Apache License, Version 2.0 (the "License"); You may not use this file except in compliance with the License. You may obtain a copy of the License at

> [http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0)

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

------------------------

# **BIO 3523: Advanced Computational Biology**

## **Module 2 : Vibe Coding**

* Instructor: [David Senseman](mailto:David.Senseman@utsa.edu), [Department of Biology, Health and the Environment](https://sciences.utsa.edu/bhe/), [UT San Antonio](https://www.utsa.edu/)

### Module Content

* Class_02_1 : Introduction to Vibe Coding
* Class_02_2 : Vibe Coding LLM-Bench App
* Class_02_3 : Vibe Coding PubMed Watch App
* **Class_02_4 : Vibe Coding for Fun**


## Google Colab Instructions

Run next code cell to map this Colab lesson's folder /content/drive to your Google Drive. This will allow you keep a copy of this Colab notebook which is your course textbook.

In [ ]:
# @title **Run this cell first**
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    Colab = True
    print("Note: Using Google CoLab")
    !curl ipinfo.io
except:
    print("**WARNING**: Your GDrive is not mapped to /content/drive ")
    print("**WARNING**: Your work will not be saved!")
    Colab = False

Mounted at /content/drive
Note: Using Google CoLab
{
  "ip": "34.185.88.215",
  "hostname": "215.88.185.34.bc.googleusercontent.com",
  "city": "Salt Lake City",
  "region": "Utah",
  "country": "US",
  "loc": "40.7608,-111.8911",
  "org": "AS396982 Google LLC",
  "postal": "84101",
  "timezone": "America/Denver",
  "readme": "https://ipinfo.io/missingauth"
}

You should see something _similar_ to the following output:
```text
Mounted at /content/drive
Note: Using Google CoLab
{
  "ip": "34.139.115.187",
  "hostname": "187.115.139.34.bc.googleusercontent.com",
  "city": "North Charleston",
  "region": "South Carolina",
  "country": "US",
  "loc": "32.8546,-79.9748",
  "org": "AS396982 Google LLC",
  "postal": "29415",
  "timezone": "America/New_York",
  "readme": "https://ipinfo.io/missingauth"
}
```

## Test Your Keys

Run the next cell to test whether your `myUTSA_ID` and your `BIO3523_Key` are correctly installed in your Colab Secrets. You will need to have both keys correctly installed in your Colab Secrets in order to submit your work for grading using Electronic Submission.

In [ ]:
# @title Test Your Keys

from google.colab import userdata
import os

# Check if myUTSA_ID is properly loaded
try:
    # 1. Get the key from Secrets
    myUTSA_ID = userdata.get('myUTSA_ID')

    # 2. Set it as an environment variable
    os.environ['myUTSA_ID'] = myUTSA_ID

    # print("myUTSA_ID is loaded and environment variable set successfully!")
    print(f"myUTSA_ID: {myUTSA_ID}")

except Exception as e:
    print(f"Error loading myUTSA_ID: {e}")
    print("Please set your myUTSA_ID in Google Colab:")
    print("1. Go to Secrets in the left sidebar (key icon)")
    print("2. Create a new secret named 'myUTSA_ID'")
    print("3. Paste your myUTSA_ID and toggle 'Notebook access' on")

# Check if BIO3523 key is properly loaded
try:
    # 1. Get the key from Secrets
    BIO3523_KEY = userdata.get('BIO3523_KEY')

    # 2. Set it as an environment variable
    os.environ['BIO3523_KEY'] = BIO3523_KEY

    #print("BIO3523 key loaded and environment variable set successfully!")
    print(f"BIO3523_KEY: {BIO3523_KEY}")

except Exception as e:
    print(f"Error loading BIO3523 key: {e}")
    print("Please set your BIO3523 key in Google Colab:")
    print("1. Go to Secrets in the left sidebar (key icon)")
    print("2. Create a new secret named 'BIO3523_KEY'")
    print("3. Paste your BIO3523 key and toggle 'Notebook access' on")

myUTSA_ID: gie856
BIO3523_KEY: BIO3523-F26-01-DA8-Y8M-GP7


If you have correctly installed both your `myUTSA ID` and your `BIO3523 Key` in your Colab Secrets, you should see something _similar_ to following but with your information:
```text
myUTSA_ID: abc123
BIO3523_KEY: BIO35233-F26-04-999-ABC-DEF
```
However, if you see an error message, you will need to fix this problem before you can submit your lesson for grading. Ask your Instructor or TA for help if you can't resolve the problem yourself --- that's what they are here for, to help you with course problems.

# **Vibe Coding for Fun**

This website was created by a person who thought it might be **fun** to vibe code an app that would show his dog in different historical costumes.

![__](https://biologicslab.co/BIO3523/images/class_02/class_02_4_image01A.png)

This fun, vibe-coded app is now a commercially profitable enterprise.

If this happens to you because of this lesson, and you become filthy rich, I hope you will remember how it all started.

## **MANDATORY YouTube Video**

Unlike most YouTube videos in these lessons, you are _required_ to watch this video as part of the lesson content. In other words, **_this vido is on the test_.**

The author of this video is Nate B. Jones. His YouTube channel, `AI News & Strategy Daily`, provides some of the highest quality and most insightful takes on the current AI environment. Like most of his videos, it is rather long (~18 min) and the subject material `dense`.

In general, I don't think teachers at any educational level, from Pre-K through College, should ever "park" their students in front of a video. On rare occaisons I have made exceptions -- this is one of these exceptions.

Another reason for "putting this video content on the test" is that this lesson provides very little factual information apart from this YouTube video.

In [ ]:
# @title **MANDATORY VIDEO--THIS CONTENT WILL BE ON THE TEST**

from IPython.display import HTML
video_id = "sLz4mAyykeE?si=kn0qVj1p1-08APQj"
HTML(f"""
<iframe width="560" height="315"
  src="https://www.youtube.com/embed/{video_id}"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
  referrerpolicy="strict-origin-when-cross-origin">
</iframe>
""")

## **Vibe Coding for Fun**

Here is an excerpt from the **_previous_** lesson:

--------------

>#### **But Wait...Think About This!**

>Here is what I want you to think about. **There are things in your life that you really do care about.** The real point of this lesson is to show you how easy it is to use your Hermes Agent to build any kind of app you like. All you have to do is change the prompts that you send to your agent. Not interested in PubMed? Just tell Hermes Agent what you are interested in. **This is exactly what we will do in the next lesson.**
----------

This the next lesson.

### **Objective of Class_02_4**

In this lesson, you are to use your Hermes Agent to vibe code an app that you find interesting and **_fun!_**

You are free to build whatever app you like, provided that follow a few simple rules descibed below.

### **Project Requirements**

**1. Title Your Session:** Give this title to your Hermes session:`Vibe Coding Project`.

**2. Store your files in a `VibeCodingProject` folder:** Tell your Hermes Agent to make a new subfolder called "VibeCodingProject" in you home directory and to put all of the code it generates for this project, in this subfolder. You will be asked, at the end of this lesson, to submit the contents of this folder for grading.

**3. Pick a "Reasonable" Model:** You are free to use any model you want for this lesson. This includes either one of the local (free) models. You might, for example, use one of the free models to generate your basic app and then use a more capable model from OpenRouter to resolve any coding or deployment issues.    

### **Suggestions**

Here are a couple of suggestions that you may find helpful.

**1. Freely Use an AI model:** In any lesson, but especially this one, you will want to have an AI ready to chat with. There are a large number of AI 'Chat' models out there you can use for help that do not require you purchase an API. Some are free like Microsoft Copilot which you can use with your UTSA Credentials. There are other models that are a little expensive (~$20/month) like `Claude Desktop` and `ChatGPT` but are **significantly** better. Finally, there are some really expensive (>\$200/month) "coding plans" like `Claude Code` and `Grok Build` from xAI, that you definitely don't need for this lesson.

For example, if you don't any idea what kind of app you should build for this lesson, just ask your AI.

If don't have any idea how to write a prompt that tells your Hermes Agent what to do, just ask your AI.

If you get a response back from your Hermes Agent that it is having trouble, ask your AI how you should respond back.   

**2. Ask your Hermes Agent:** Depending up the model you are using, your Hermes Agent can be really smart. Instead of asking "your AI" for help, just ask your Hermes Agent!

## **Start a New Session**

Follow these steps to get started on your project.

Use this command to start an instance of Hermes Agent CLI interface:
```text
hermes-agent tui
```
This will bring up your Hermes Agent CLI.

##### **Name your session**

To give your session a title, use this slash command:
```text
/title Vibe Coding Project
```
Your session is now called `Vibe Coding Project`.

##### **Switch model**

For this lesson you should use  a pretty good model--not a frontier model--but a model that canhandle the coding, tool calls and code testing for a reasonably complex application.

In the input window give the `/model` command:
```text
/model
```
This will bring up the `Select provider` setup menu:

![__](https://biologicslab.co/BIO3523/images/class_02/class_02_2_image04A.png)

Scroll to the top of the list, until you see the `OpenRouter` option:

![__](https://biologicslab.co/BIO3523/images/class_02/class_02_2_image05A.png)

Press **`Enter`** to select the OpenRouter option.

You should now be presented with a list of models that are currently available with your `OpenRouter API key`, starting alphabetically with
```text
▸ 1. anthropic/claude-fable-5.1
```

![__](https://biologicslab.co/BIO3523/images/class_02/class_02_2_image06A.png)

We don't want to use this particular Anthropic model (it's too powerful and too expensive), so scroll down the list to find the model that you want to use.

#### **SUGGESTIONS:**

1. Before you pick a model, you might want to go to your OpenRouter Account and check out the available models and how much they cost.

2. While you are there, you might also want to add some money to your `Credit` balance if it's low -- you don't want your Hermes Agent to "die" in the middle of processing your prompt because your credit balance went to \$0.  

## **START CODING**

Time to start coding. Don't forget to tell your Hermes Agent to make a new subfolder called "VibeCodingProject" in you home directory and put all of the code it generates in this subfolder. (Note: Never have a space in any folder name.)

Have Fun!

## **Exercise 1 - Content of VibeCodingProject**

When you have finished your Vibe Coding Project, exit the Hermes Agent CLI and return to your LXC terminal.

To display the various code files that your Hermes Agent created for this lesson, give this command:
```text
ls -la ~/VibeCodingProject
```

Your output should look somewhat _similar_ to the following output:
```text
abc123@abc123:~$ ls -la ~/VibeCodingProject
total 57
drwxrwxr-x  4 abc123 abc123    9 Sep 13 00:08 ./
drwxr-x--- 12 abc123 abc123   26 Sep 19 19:30 ../
-rw-------  1 abc123 abc123   94 Sep  8 16:46 .env
-rw-rw-r--  1 abc123 abc123    5 Sep  8 16:49 .gitignore
drwxrwxr-x  5 abc123 abc123   10 Sep 12 20:02 .venv/
drwxrwxr-x  2 abc123 abc123    3 Sep  7 22:57 __pycache__/
-rw-rw-r--  1 abc123 abc123 1131 Sep  8 17:02 check_credits.py
-rw-rw-r--  1 abc123 abc123  672 Sep  8 16:52 load_key.py
-rw-rw-r--  1 abc123 abc123 2119 Sep 13 00:08 vibeFun_app.py
abc123@abc123:~$

```

In [ ]:
# @title Exercise 1 - Content of VibeCodingProject

# Paste the content of your VibeCodingProject immediately below the next line of code:
terminal_output = r"""

abc123@abc123:~$ ls -la ~/VibeCodingProject
total 57
drwxrwxr-x  4 abc123 abc123    9 Sep 13 00:08 ./
drwxr-x--- 12 abc123 abc123   26 Sep 19 19:30 ../
-rw-------  1 abc123 abc123   94 Sep  8 16:46 .env
-rw-rw-r--  1 abc123 abc123    5 Sep  8 16:49 .gitignore
drwxrwxr-x  5 abc123 abc123   10 Sep 12 20:02 .venv/
drwxrwxr-x  2 abc123 abc123    3 Sep  7 22:57 __pycache__/
-rw-rw-r--  1 abc123 abc123 1131 Sep  8 17:02 check_credits.py
-rw-rw-r--  1 abc123 abc123  672 Sep  8 16:52 load_key.py
-rw-rw-r--  1 abc123 abc123 2119 Sep 13 00:08 vibeFun_app.py
abc123@abc123:~$

"""

# Display the stored text cleanly back to the student
print("Successfully logged terminal output:")
print(terminal_output)

Successfully logged terminal output:


abc123@abc123:~$ ls -la ~/VibeCodingProject
total 57
drwxrwxr-x  4 abc123 abc123    9 Sep 13 00:08 ./
drwxr-x--- 12 abc123 abc123   26 Sep 19 19:30 ../
-rw-------  1 abc123 abc123   94 Sep  8 16:46 .env
-rw-rw-r--  1 abc123 abc123    5 Sep  8 16:49 .gitignore
drwxrwxr-x  5 abc123 abc123   10 Sep 12 20:02 .venv/
drwxrwxr-x  2 abc123 abc123    3 Sep  7 22:57 __pycache__/
-rw-rw-r--  1 abc123 abc123 1131 Sep  8 17:02 check_credits.py
-rw-rw-r--  1 abc123 abc123  672 Sep  8 16:52 load_key.py
-rw-rw-r--  1 abc123 abc123 2119 Sep 13 00:08 vibeFun_app.py
abc123@abc123:~$




If the code is correct, you should see something _similar_ to the following output:

```text
Successfully logged terminal output:

abc123@abc123:~$ ls -la ~/VibeCodingProject
total 57
drwxrwxr-x  4 abc123 abc123    9 Sep 13 00:08 ./
drwxr-x--- 12 abc123 abc123   26 Sep 19 19:30 ../
-rw-------  1 abc123 abc123   94 Sep  8 16:46 .env
-rw-rw-r--  1 abc123 abc123    5 Sep  8 16:49 .gitignore
drwxrwxr-x  5 abc123 abc123   10 Sep 12 20:02 .venv/
drwxrwxr-x  2 abc123 abc123    3 Sep  7 22:57 __pycache__/
-rw-rw-r--  1 abc123 abc123 1131 Sep  8 17:02 check_credits.py
-rw-rw-r--  1 abc123 abc123  672 Sep  8 16:52 load_key.py
-rw-rw-r--  1 abc123 abc123 2119 Sep 13 00:08 vibeFun_app.py
abc123@abc123:~$
```

# **Electronic Submission**

When you run the code in the cell below, it will grade your Colab notebook and tell you your pending grade as it currently stands. You will be given the choice to either submit your notebook for final grading or the option to continue your work on one (or more) Exercises.

Grant Access to your Colab Secrets if you are asked to do so.

In [ ]:
# @title  Electronic Submission

import urllib.request
import ssl
import time

url = "https://biologicslab.co/BIO3523/backend_code/validate.py?v=" + str(time.time())
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE
req = urllib.request.Request(
    url,
    headers={
        "Cache-Control": "no-cache, no-store, must-revalidate",
        "Pragma": "no-cache",
        "Expires": "0"
    }
)
with urllib.request.urlopen(req, context=ctx) as r:
    exec(r.read().decode("utf-8"))
main()

UTSA ID: gie856 ✅
BIO3523 Key  ✅

Grading notebook — this may take a moment…
✅  Preliminary grading complete  (ID: BIO3523_6ab14f9b7eb9b)
❌  Could not grade notebook: Solution notebook not found: /var/www/html/BIO3523/AnswerKeys/BIO3523_Class_02_4_Solutions.ipynb


Output()